name: Deploy

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: { }

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy CDK stacks
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      id-token: write
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18.0'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::YOURROLE:role/GithubActionsDeployRole
          aws-region: us-west-2
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run tests and build binaries
        run: make test all
      - name: Install dependencies
        run: npm install --ci
        working-directory: ./cdk
      - name: CDK deploy
        run: npx cdk deploy --all --require-approval never
        working-directory: ./cdk

  changelog:
    runs-on: ubuntu-latest
    needs: deploy
    permissions:
      actions: write
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - name: Generate CHANGELOG.md
        uses: TriPSs/conventional-changelog-action@v3
        with:
          release-count: '10'
          git-message: 'chore(ci): changelog update'
