name: Deploy

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy CDK stacks
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      id-token: write
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::YOURROLE:role/GithubActionsDeployRole
          aws-region: us-west-2
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install --ci
      - name: Run tests and build binaries
        run: make test all
      - name: CDK deploy
        run: npx cdk deploy --all --require-approval never

  changelog:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.PAT }}
          allow-initial-development-versions: true
          changelog-file: CHANGELOG.md
          update-file: package.json
          changelog-generator-opt: "emojis=true"
          force-bump-patch-version: true
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore(ci): commit changes from go-semantic-release'
          file_pattern: CHANGELOG.md package.json
